apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: example-daemon
spec:
  replicas: 3
  selector:
    matchLabels:
      name: example-daemon
  template:
     metadata:
       labels:
        name: example-daemon
     spec:   
       containers:
         - name: nginx
           image: nginx











































