apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
spec:
  containers:
  - image: justinhuang402490/k8s:web-app
    name: web-app
    ports:
      - containerPort: 3000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
