apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: taint-pod
  name: taint-pod
spec:
  containers:
  - image: nginx
    name: taint-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
